sysdeps update
git-svn-id: file:///source/coreland/integer/trunk@2610 6e7d7e42-f3d6-da11-80d8-00d0b73f4485

diff --git a/cc-compile b/cc-compile
--- a/cc-compile
+++ b/cc-compile
@@ -6,15 +6,59 @@ then
   exit 1
 fi
 
-CC=`head -n 1 conf-cc`
-if [ $? -ne 0 ]
+#
+# Assume source is being cross compiled if there is a cross-compiler
+# defined.
+#
+
+if [ -f conf-x-cc ]
 then
-  echo "fatal: could not read conf-cc" 1>&2
-  exit 1
+  CC=`head -n 1 conf-x-cc`
+  if [ $? -ne 0 ]
+  then
+    echo "fatal: could not read conf-x-cc" 1>&2
+    exit 1
+  fi
+  SYSTYPE=`head -n 1 conf-x-systype`
+  if [ $? -ne 0 ]
+  then
+    echo "fatal: could not read conf-x-systype" 1>&2
+    exit 1
+  fi
+  CCTYPE=`head -n 1 conf-x-cctype`
+  if [ $? -ne 0 ]
+  then
+    echo "fatal: could not read conf-x-cctype" 1>&2
+    exit 1
+  fi
+  CFLAGS="${CFLAGS} `head -n 1 conf-x-cflags 2>/dev/null`"
+else
+  CC=`head -n 1 conf-cc`
+  if [ $? -ne 0 ]
+  then
+    echo "fatal: could not read conf-cc" 1>&2
+    exit 1
+  fi
+  SYSTYPE=`head -n 1 conf-systype`
+  if [ $? -ne 0 ]
+  then
+    echo "fatal: could not read conf-systype" 1>&2
+    exit 1
+  fi
+  CCTYPE=`head -n 1 conf-cctype`
+  if [ $? -ne 0 ]
+  then
+    echo "fatal: could not read conf-cctype" 1>&2
+    exit 1
+  fi
 fi
+
 CFLAGS="${CFLAGS} `head -n 1 conf-cflags 2>/dev/null`"
 
-# read in optional flag file
+#
+# Read global flag file list, if present.
+#
+
 if [ -f "conf-ccfflist" ]
 then
   for f in `cat "conf-ccfflist"`
@@ -24,11 +68,18 @@ then
   done
 fi
 
+#
+# Extract base name of given source file.
+#
+
 out=`echo "$1" | awk -F. '{print $1}'`
 src="$1"
 shift
 
-# read in optional flag file
+#
+# Read local flag file list, if present.
+#
+
 if [ -f "${out}.iff" ]
 then
   for f in `cat "${out}.iff"`
diff --git a/cc-link b/cc-link
--- a/cc-link
+++ b/cc-link
@@ -6,13 +6,58 @@ then
   exit 1
 fi
 
-LD=`head -n 1 conf-ld`
-if [ $? -ne 0 ]
+#
+# Assume source is being cross linked if there is a cross-linker
+# defined.
+#
+
+if [ -f conf-x-ld ]
 then
-  echo "fatal: could not read conf-ld" 1>&2
-  exit 1
+  LD=`head -n 1 conf-x-ld`
+  if [ $? -ne 0 ]
+  then
+    echo "fatal: could not read conf-x-ld" 1>&2
+    exit 1
+  fi
+  SYSTYPE=`head -n 1 conf-x-systype`
+  if [ $? -ne 0 ]
+  then
+    echo "fatal: could not read conf-x-systype" 1>&2
+    exit 1
+  fi  
+  LDTYPE=`head -n 1 conf-x-ldtype`
+  if [ $? -ne 0 ]
+  then
+    echo "fatal: could not read conf-x-ldtype" 1>&2
+    exit 1
+  fi
+  LDFLAGS="${LDFLAGS} `head -n 1 conf-x-ldflags 2>/dev/null`"
+else
+  LD=`head -n 1 conf-ld`
+  if [ $? -ne 0 ]
+  then
+    echo "fatal: could not read conf-ld" 1>&2
+    exit 1
+  fi
+  SYSTYPE=`head -n 1 conf-systype`
+  if [ $? -ne 0 ]
+  then
+    echo "fatal: could not read conf-systype" 1>&2
+    exit 1
+  fi  
+  LDTYPE=`head -n 1 conf-ldtype`
+  if [ $? -ne 0 ]
+  then
+    echo "fatal: could not read conf-ldtype" 1>&2
+    exit 1
+  fi
 fi
+
 LDFLAGS="${LDFLAGS} `head -n 1 conf-ldflags 2>/dev/null`"
+
+#
+# Read global flag file list, if present.
+#
 
 if [ -f "conf-ldfflist" ]
 then
@@ -26,7 +71,10 @@ fi
 out="$1"
 shift
 
-# read in optional flag file
+#
+# Read local flag file list, if present.
+#
+
 if [ -f "${out}.lff" ]
 then
   for f in `cat "${out}.lff"`
